// generated by the @nuxtjs/tailwindcss <https://github.com/nuxt-modules/tailwindcss> module at 4/1/2025, 3:34:45 PM
import configMerger from "@nuxtjs/tailwindcss/merger";

;
const config = [
{"content":{"files":["C:/xampp/htdocs/uandc-erp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/uandc-erp/components/global/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/uandc-erp/components/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/uandc-erp/layouts/**/*.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/uandc-erp/plugins/**/*.{js,ts,mjs}","C:/xampp/htdocs/uandc-erp/composables/**/*.{js,ts,mjs}","C:/xampp/htdocs/uandc-erp/utils/**/*.{js,ts,mjs}","C:/xampp/htdocs/uandc-erp/pages/about.vue","C:/xampp/htdocs/uandc-erp/pages/index.vue","C:/xampp/htdocs/uandc-erp/{A,a}pp.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/uandc-erp/{E,e}rror.{vue,js,jsx,mjs,ts,tsx}","C:/xampp/htdocs/uandc-erp/app.config.{js,ts,mjs}"]}},
{}
].reduce((acc, curr) => configMerger(acc, curr), {});

const resolvedConfig = config;

export default resolvedConfig;